spring:
  application:
    name: employee-management-system

  datasource:
    url: jdbc:postgresql://localhost:5432/ems_db
    username: postgres
    password: Yash@1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        format_sql: true


server:
  port: 8080